[phases.setup]
nixPkgs = ["php", "composer"]

[phases.build]
commands = [
  "composer install --no-dev --optimize-autoloader",
  "php artisan config:cache"
]

[phases.start]
cmd = "php artisan serve --host=0.0.0.0 --port=8000"

[ports]
http = 8000
